
Search...

LOGIN SIGN UP
Vigjjvh
Rdp Method By H4k3R 🔥
VIGJJVH
JAN 20TH, 2025
3,395
0
NEVER
ADD COMMENT
Not a member of Pastebin yet? Sign Up, it unlocks many cool features!
0.49 KB | None |  
  
name: Avica
 
on:
  workflow_dispatch:
 
jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 360
 
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://gitlab.com/raposabrty/pcrdp/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat
 
      - name: Show Website
        run: cmd /c show.bat
 
      - name: Time Counter
        run: cmd /c loop.bat
 
